name: Convert Markdown to DOCX

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.md'
      - '.github/workflows/build-docx.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - '**.md'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup pandoc
      uses: r-lib/actions/setup-pandoc@v2
      with:
        pandoc-version: '3.1.9' # Используем последнюю стабильную версию
    
    
    - name: Create output directory
      run: mkdir -p output
    
    - name: Convert ct_arteriohepaticography.md to DOCX
      run: |
        pandoc ct_arteriohepaticography.md \
          -f markdown \
          -t docx \
          --reference-doc=reference.docx \
          --filter pandoc-citeproc \
          --csl=gost-r-7-0-5-2008-numeric-iaa.csl \
          --bibliography=references.bib \
          --toc \
          --toc-depth=3 \
          --number-sections \
          -o output/ct_arteriohepaticography.docx
      continue-on-error: true
    
    - name: Convert all markdown files (fallback without bibliography)
      run: |
        for file in *.md; do
          if [ -f "$file" ]; then
            output_name="output/${file%.md}.docx"
            echo "Converting $file to $output_name"
            pandoc "$file" \
              -f markdown \
              -t docx \
              --toc \
              --toc-depth=3 \
              --number-sections \
              -o "$output_name" || echo "Failed to convert $file"
          fi
        done
    
    - name: Upload DOCX artifacts
      uses: actions/upload-artifact@v4
      with:
        name: docx-documents
        path: output/*.docx
        retention-days: 30
    
    - name: Commit DOCX files back to repository (optional)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output/*.docx
        git diff --staged --quiet || git commit -m "Auto-generate DOCX files from Markdown [skip ci]"
        git push || echo "No changes to push"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}